In [ ]:
!pip install selenium
!pip install webdriver_manager

Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (4.15.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.23.1)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Requirement already satisfied: webdriver_manager in /usr/local/lib/python3.10/dist-packages (4.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (2.31.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (1.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (2023.7.22)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

class Scraper():

    def menu(self):
        menu = ("""
    Escoge el país:
    1. Argentina
    2. Bolivia
    3. Brasil
    4. Chile
    5. Colombia
    6. Costa Rica
    7. Dominicana
    8. Ecuador
    9. Guatemala
    10. Honduras
    11. México
    12. Nicaragua
    13. Panamá
    14. Paraguay
    15. Perú
    16. Salvador
    17. Uruguay
    18. Venezuela
        """)

        valid_options = list(range(1, 19))

        while True:
            print(menu)
            opcion = int(input('Número de país (Ejemplo: 5): '))

            if opcion in valid_options:

                urls = {
                1: 'https://listado.mercadolibre.com.ar/',
                2: 'https://listado.mercadolibre.com.bo/',
                3: 'https://listado.mercadolibre.com.br/',
                4: 'https://listado.mercadolibre.cl/',
                5: 'https://listado.mercadolibre.com.co/',
                6: 'https://listado.mercadolibre.com.cr/',
                7: 'https://listado.mercadolibre.com.do/',
                8: 'https://listado.mercadolibre.com.ec/',
                9: 'https://listado.mercadolibre.com.gt/',
                10: 'https://listado.mercadolibre.com.hn/',
                11: 'https://listado.mercadolibre.com.mx/',
                12: 'https://listado.mercadolibre.com.ni/',
                13: 'https://listado.mercadolibre.com.pa/',
                14: 'https://listado.mercadolibre.com.py/',
                15: 'https://listado.mercadolibre.com.pe/',
                16: 'https://listado.mercadolibre.com.sv/',
                17: 'https://listado.mercadolibre.com.uy/',
                18: 'https://listado.mercadolibre.com.ve/',
                }

                self.base_url = urls[opcion]
                break
            else:
                print("Escoge un número del 1 al 18")



    def scraping(self):
        # User search
        product_name = input("\nProducto: ")
        # Clean the user input
        cleaned_name = product_name.replace(" ", "-").lower()
        # Create the urls to scrap
        urls = [self.base_url + cleaned_name]

        page_number = 50
        for i in range(0, 10000, 50):
            urls.append(f"{self.base_url}{cleaned_name}_Desde_{page_number + 1}_NoIndex_True")
            page_number += 50

        # create a list to save the data
        self.data = []
        # create counter
        c = 1

        # Iterate over each url
        for i, url in enumerate(urls, start=1):

            # Get the html of the page
            response = requests.get(url)
            soup = BeautifulSoup(response.text, 'html.parser')

            # take all posts
            content = soup.find_all('li', class_='ui-search-layout__item')

            # Check if there's no content to scrape
            if not content:
                print("\nTermino el scraping.")
                break

            print(f"\nScrapeando pagina numero {i}. {url}")


            # iteration to scrape posts
            for post in content:
                # get the title
                title = post.find('h2').text
                # get the price
                price = post.find('span', class_='andes-money-amount__fraction').text
                # Precio descuento <span class="ui-search-price__discount">25% OFF</span>
                perc_desc = post.find('span', class_='ui-search-price__discount')
                # Calificaciones y nota
                count = post.find('span', class_="andes-visually-hidden")
                #count =  <span class="ui-search-reviews__amount" aria-hidden="true">(71)</span>

                # get the url post
                post_link = post.find("a")["href"]
                # get the url image
                try:
                    img_link = post.find("img")["data-src"]
                except:
                    img_link = post.find("img")["src"]

                # show the data already scraped
                # print(f"{c}. {title}, {price}, {post_link}, {img_link}")

                # save in a dictionary
                post_data = {
                    "title": title,
                    "price": price,
                    "perc_desc":perc_desc,
                    "count": count,
                    "post link": post_link,
                    "image link": img_link
                }
                # save the dictionaries in a list
                self.data.append(post_data)
                c += 1

    def export_to_csv(self):
        # export to a csv file
        df = pd.DataFrame(self.data)
        df.to_csv(r"/content/sample_data/mercadolibre_scraped_data.csv", sep=";")

if __name__ == "__main__":
    s = Scraper()
    s.menu()
    s.scraping()
    s.export_to_csv()

# <span class="ui-pdp-subtitle">Nuevo  |  +5 vendidos</span>
# <span class="andes-visually-hidden">Calificación 4.7 de 5. 71 opiniones.</span>

    Escoge el país:
    1. Argentina
    2. Bolivia
    3. Brasil
    4. Chile
    5. Colombia
    6. Costa Rica
    7. Dominicana
    8. Ecuador
    9. Guatemala
    10. Honduras
    11. México
    12. Nicaragua
    13. Panamá
    14. Paraguay
    15. Perú
    16. Salvador
    17. Uruguay
    18. Venezuela

Número de país (Ejemplo: 5): 5

Producto: luces navidad

Scrapeando pagina numero 1. https://listado.mercadolibre.com.co/luces-navidad

Scrapeando pagina numero 2. https://listado.mercadolibre.com.co/luces-navidad_Desde_51_NoIndex_True

Scrapeando pagina numero 3. https://listado.mercadolibre.com.co/luces-navidad_Desde_101_NoIndex_True

Scrapeando pagina numero 4. https://listado.mercadolibre.com.co/luces-navidad_Desde_151_NoIndex_True

Scrapeando pagina numero 5. https://listado.mercadolibre.com.co/luces-navidad_Desde_201_NoIndex_True

Scrapeando pagina numero 6. https://listado.mercadolibre.com.co/luces-navidad_Desde_251_NoIndex_True

Scrapeando pagina numero 7. https://listado.mercadolibre.com.co/luces-navidad_Desde_301_NoIndex_True

Scrapeando pagina numero 8. https://listado.mercadolibre.com.co/luces-navidad_Desde_351_NoIndex_True

Scrapeando pagina numero 9. https://listado.mercadolibre.com.co/luces-navidad_Desde_401_NoIndex_True

Scrapeando pagina numero 10. https://listado.mercadolibre.com.co/luces-navidad_Desde_451_NoIndex_True

Scrapeando pagina numero 11. https://listado.mercadolibre.com.co/luces-navidad_Desde_501_NoIndex_True

Scrapeando pagina numero 12. https://listado.mercadolibre.com.co/luces-navidad_Desde_551_NoIndex_True

Scrapeando pagina numero 13. https://listado.mercadolibre.com.co/luces-navidad_Desde_601_NoIndex_True

Scrapeando pagina numero 14. https://listado.mercadolibre.com.co/luces-navidad_Desde_651_NoIndex_True

Scrapeando pagina numero 15. https://listado.mercadolibre.com.co/luces-navidad_Desde_701_NoIndex_True

Scrapeando pagina numero 16. https://listado.mercadolibre.com.co/luces-navidad_Desde_751_NoIndex_True

Scrapeando pagina numero 17. https://listado.mercadolibre.com.co/luces-navidad_Desde_801_NoIndex_True

Scrapeando pagina numero 18. https://listado.mercadolibre.com.co/luces-navidad_Desde_851_NoIndex_True

Scrapeando pagina numero 19. https://listado.mercadolibre.com.co/luces-navidad_Desde_901_NoIndex_True

Scrapeando pagina numero 20. https://listado.mercadolibre.com.co/luces-navidad_Desde_951_NoIndex_True

Scrapeando pagina numero 21. https://listado.mercadolibre.com.co/luces-navidad_Desde_1001_NoIndex_True

Scrapeando pagina numero 22. https://listado.mercadolibre.com.co/luces-navidad_Desde_1051_NoIndex_True

Scrapeando pagina numero 23. https://listado.mercadolibre.com.co/luces-navidad_Desde_1101_NoIndex_True

Scrapeando pagina numero 24. https://listado.mercadolibre.com.co/luces-navidad_Desde_1151_NoIndex_True

Scrapeando pagina numero 25. https://listado.mercadolibre.com.co/luces-navidad_Desde_1201_NoIndex_True

Scrapeando pagina numero 26. https://listado.mercadolibre.com.co/luces-navidad_Desde_1251_NoIndex_True

Scrapeando pagina numero 27. https://listado.mercadolibre.com.co/luces-navidad_Desde_1301_NoIndex_True

Scrapeando pagina numero 28. https://listado.mercadolibre.com.co/luces-navidad_Desde_1351_NoIndex_True

Scrapeando pagina numero 29. https://listado.mercadolibre.com.co/luces-navidad_Desde_1401_NoIndex_True

Scrapeando pagina numero 30. https://listado.mercadolibre.com.co/luces-navidad_Desde_1451_NoIndex_True

Scrapeando pagina numero 31. https://listado.mercadolibre.com.co/luces-navidad_Desde_1501_NoIndex_True

Scrapeando pagina numero 32. https://listado.mercadolibre.com.co/luces-navidad_Desde_1551_NoIndex_True

Scrapeando pagina numero 33. https://listado.mercadolibre.com.co/luces-navidad_Desde_1601_NoIndex_True

Scrapeando pagina numero 34. https://listado.mercadolibre.com.co/luces-navidad_Desde_1651_NoIndex_True

Scrapeando pagina numero 35. https://listado.mercadolibre.com.co/luces-navidad_Desde_1701_NoIndex_True

Scrapeando pagina numero 36. https://listado.mercadolibre.com.co/luces-navidad_Desde_1751_NoIndex_True

Scrapeando pagina numero 37. https://listado.mercadolibre.com.co/luces-navidad_Desde_1801_NoIndex_True

Scrapeando pagina numero 38. https://listado.mercadolibre.com.co/luces-navidad_Desde_1851_NoIndex_True

Scrapeando pagina numero 39. https://listado.mercadolibre.com.co/luces-navidad_Desde_1901_NoIndex_True

Scrapeando pagina numero 40. https://listado.mercadolibre.com.co/luces-navidad_Desde_1951_NoIndex_True

Scrapeando pagina numero 41. https://listado.mercadolibre.com.co/luces-navidad_Desde_2001_NoIndex_True

Termino el scraping.

In [ ]:
# Lee el archivo CSV y crea un DataFrame
df = pd.read_csv('/content/sample_data/mercadolibre_scraped_data.csv', delimiter=";")
df

,Unnamed: 0,title,price,perc_desc,count,post link,image link
0,0,Extensión Luces Led Estrella X6 M Luz Navidad ...,97.900,"<span class=""ui-search-price__discount"">7% OFF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_820360-MCO7...
1,1,Luces De Navidad Cortina Luz Decoracion Navide...,59.990,"<span class=""ui-search-price__discount"">16% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_962071-MCO7...
2,2,Luces De Navidad Cortina Luz Decoracion Navide...,62.990,"<span class=""ui-search-price__discount"">25% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-82124...,https://http2.mlstatic.com/D_NQ_NP_730331-MCO4...
3,3,Luz De Navidad Cortina 3m X 45 Cm Luces Varios...,21.900,"<span class=""ui-search-price__discount"">6% OFF...","<span aria-hidden=""true"" class=""andes-visually...",https://articulo.mercadolibre.com.co/MCO-95903...,https://http2.mlstatic.com/D_NQ_NP_636753-MCO5...
4,4,Luz Lineal Ledl 100 Mts 1000 Led Luces Navidad...,187.000,NaN,"<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-99284...,https://http2.mlstatic.com/D_NQ_NP_658192-MCO5...
...,...,...,...,...,...,...,...
2291,2291,Luz Cascada 6x2m 480 Led Luces Navidad Multico...,164.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-99282...,https://http2.mlstatic.com/D_NQ_NP_931544-MCO5...
2292,2292,Luces Led Estrellas Y Copos 260 Luces 3m Navid...,109.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10202...,https://http2.mlstatic.com/D_NQ_NP_981457-MCO5...
2293,2293,Cortina Led 3m X 45 Cm 100 Led Multicolor Navi...,27.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10209...,https://http2.mlstatic.com/D_NQ_NP_892430-MCO4...
2294,2294,Cortina Led Intercalada 10 M Navidad 360 Led F...,84.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10633...,https://http2.mlstatic.com/D_NQ_NP_875739-MCO5...
2295,2295,"Cortina Micro Led Ramal 6x1,8 M 1440 Led Navid...",199.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-11158...,https://http2.mlstatic.com/D_NQ_NP_836920-MCO5...

In [ ]:
import re

# Función para extraer las calificaciones y opiniones usando expresiones regulares
def extraer_calificacion_opiniones(texto):
    if isinstance(texto, str):  # Verifica si es una cadena de texto
        calificacion_match = re.search(r'Calificación (\d+\.\d+)', texto)
        opiniones_match = re.search(r'(\d+)\s*opiniones?', texto)

        calificacion = calificacion_match.group(1) if calificacion_match else None
        opiniones = int(opiniones_match.group(1)) if opiniones_match else None

        return calificacion, opiniones
    else:
        return None, None

# Aplicar la función a la columna 'count' y crear nuevas columnas 'calificacion' y 'opiniones'
df[['calificacion', 'opiniones']] = df['count'].apply(lambda x: pd.Series(extraer_calificacion_opiniones(x)))

# Imprimir el DataFrame resultante
print(df)

      Unnamed: 0                                              title    price  \
0              0  Extensión Luces Led Estrella X6 M Luz Navidad ...   97.900
1              1  Luces De Navidad Cortina Luz Decoracion Navide...   59.990
2              2  Luces De Navidad Cortina Luz Decoracion Navide...   62.990
3              3  Luz De Navidad Cortina 3m X 45 Cm Luces Varios...   21.900
4              4  Luz Lineal Ledl 100 Mts 1000 Led Luces Navidad...  187.000
...          ...                                                ...      ...
2291        2291  Luz Cascada 6x2m 480 Led Luces Navidad Multico...  164.900
2292        2292  Luces Led Estrellas Y Copos 260 Luces 3m Navid...  109.900
2293        2293  Cortina Led 3m X 45 Cm 100 Led Multicolor Navi...   27.900
2294        2294  Cortina Led Intercalada 10 M Navidad 360 Led F...   84.900
2295        2295  Cortina Micro Led Ramal 6x1,8 M 1440 Led Navid...  199.900

                                              perc_desc  \
0     <span class="ui-search-price__discount">7% OFF...
1     <span class="ui-search-price__discount">16% OF...
2     <span class="ui-search-price__discount">25% OF...
3     <span class="ui-search-price__discount">6% OFF...
4                                                   NaN
...                                                 ...
2291                                                NaN
2292                                                NaN
2293                                                NaN
2294                                                NaN
2295                                                NaN

                                                  count  \
0     <span class="andes-visually-hidden">Calificaci...
1     <span class="andes-visually-hidden">Calificaci...
2     <span class="andes-visually-hidden">Calificaci...
3     <span aria-hidden="true" class="andes-visually...
4     <span class="andes-visually-hidden">Calificaci...
...                                                 ...
2291                                                NaN
2292                                                NaN
2293                                                NaN
2294                                                NaN
2295                                                NaN

                                              post link  \
0     https://click1.mercadolibre.com.co/mclics/clic...
1     https://click1.mercadolibre.com.co/mclics/clic...
2     https://articulo.mercadolibre.com.co/MCO-82124...
3     https://articulo.mercadolibre.com.co/MCO-95903...
4     https://articulo.mercadolibre.com.co/MCO-99284...
...                                                 ...
2291  https://articulo.mercadolibre.com.co/MCO-99282...
2292  https://articulo.mercadolibre.com.co/MCO-10202...
2293  https://articulo.mercadolibre.com.co/MCO-10209...
2294  https://articulo.mercadolibre.com.co/MCO-10633...
2295  https://articulo.mercadolibre.com.co/MCO-11158...

                                             image link calificacion  \
0     https://http2.mlstatic.com/D_NQ_NP_820360-MCO7...          4.8
1     https://http2.mlstatic.com/D_NQ_NP_962071-MCO7...          4.8
2     https://http2.mlstatic.com/D_NQ_NP_730331-MCO4...          4.7
3     https://http2.mlstatic.com/D_NQ_NP_636753-MCO5...         None
4     https://http2.mlstatic.com/D_NQ_NP_658192-MCO5...          4.6
...                                                 ...          ...
2291  https://http2.mlstatic.com/D_NQ_NP_931544-MCO5...         None
2292  https://http2.mlstatic.com/D_NQ_NP_981457-MCO5...         None
2293  https://http2.mlstatic.com/D_NQ_NP_892430-MCO4...         None
2294  https://http2.mlstatic.com/D_NQ_NP_875739-MCO5...         None
2295  https://http2.mlstatic.com/D_NQ_NP_836920-MCO5...         None

      opiniones
0          45.0
1          10.0
2         223.0
3           NaN
4          25.0
...         ...
2291        NaN
2292        NaN
2293        NaN
2294        NaN
2295        NaN

[2296 rows x 9 columns]

In [ ]:
df

,Unnamed: 0,title,price,perc_desc,count,post link,image link,calificacion,opiniones
0,0,Extensión Luces Led Estrella X6 M Luz Navidad ...,97.900,"<span class=""ui-search-price__discount"">7% OFF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_820360-MCO7...,4.8,45.0
1,1,Luces De Navidad Cortina Luz Decoracion Navide...,59.990,"<span class=""ui-search-price__discount"">16% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_962071-MCO7...,4.8,10.0
2,2,Luces De Navidad Cortina Luz Decoracion Navide...,62.990,"<span class=""ui-search-price__discount"">25% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-82124...,https://http2.mlstatic.com/D_NQ_NP_730331-MCO4...,4.7,223.0
3,3,Luz De Navidad Cortina 3m X 45 Cm Luces Varios...,21.900,"<span class=""ui-search-price__discount"">6% OFF...","<span aria-hidden=""true"" class=""andes-visually...",https://articulo.mercadolibre.com.co/MCO-95903...,https://http2.mlstatic.com/D_NQ_NP_636753-MCO5...,None,NaN
4,4,Luz Lineal Ledl 100 Mts 1000 Led Luces Navidad...,187.000,NaN,"<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-99284...,https://http2.mlstatic.com/D_NQ_NP_658192-MCO5...,4.6,25.0
...,...,...,...,...,...,...,...,...,...
2291,2291,Luz Cascada 6x2m 480 Led Luces Navidad Multico...,164.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-99282...,https://http2.mlstatic.com/D_NQ_NP_931544-MCO5...,None,NaN
2292,2292,Luces Led Estrellas Y Copos 260 Luces 3m Navid...,109.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10202...,https://http2.mlstatic.com/D_NQ_NP_981457-MCO5...,None,NaN
2293,2293,Cortina Led 3m X 45 Cm 100 Led Multicolor Navi...,27.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10209...,https://http2.mlstatic.com/D_NQ_NP_892430-MCO4...,None,NaN
2294,2294,Cortina Led Intercalada 10 M Navidad 360 Led F...,84.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10633...,https://http2.mlstatic.com/D_NQ_NP_875739-MCO5...,None,NaN
2295,2295,"Cortina Micro Led Ramal 6x1,8 M 1440 Led Navid...",199.900,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-11158...,https://http2.mlstatic.com/D_NQ_NP_836920-MCO5...,None,NaN

In [ ]:
import numpy as np
# Función para extraer el descuento de la cadena usando expresiones regulares
def extraer_descuento(cadena):
    if pd.isnull(cadena) or not isinstance(cadena, str):
        return np.nan
    else:
        # Busca el patrón de números seguido por '% OFF' y extrae el número
        match = re.search(r'(\d+)% OFF', cadena)
        if match:
            return int(match.group(1))  # Devuelve el número encontrado
        else:
            return np.nan

# Aplicar la función a la columna 'count' y crear una nueva columna 'descuento'
df['descuento'] = df['perc_desc'].apply(extraer_descuento)

# Mostrar el DataFrame con la nueva columna 'descuento'
print(df)

      Unnamed: 0                                              title    price  \
0              0  Extensión Luces Led Estrella X6 M Luz Navidad ...   97.900
1              1  Luces De Navidad Cortina Luz Decoracion Navide...   59.990
2              2  Luces De Navidad Cortina Luz Decoracion Navide...   62.990
3              3  Luz De Navidad Cortina 3m X 45 Cm Luces Varios...   21.900
4              4  Luz Lineal Ledl 100 Mts 1000 Led Luces Navidad...  187.000
...          ...                                                ...      ...
2291        2291  Luz Cascada 6x2m 480 Led Luces Navidad Multico...  164.900
2292        2292  Luces Led Estrellas Y Copos 260 Luces 3m Navid...  109.900
2293        2293  Cortina Led 3m X 45 Cm 100 Led Multicolor Navi...   27.900
2294        2294  Cortina Led Intercalada 10 M Navidad 360 Led F...   84.900
2295        2295  Cortina Micro Led Ramal 6x1,8 M 1440 Led Navid...  199.900

                                              perc_desc  \
0     <span class="ui-search-price__discount">7% OFF...
1     <span class="ui-search-price__discount">16% OF...
2     <span class="ui-search-price__discount">25% OF...
3     <span class="ui-search-price__discount">6% OFF...
4                                                   NaN
...                                                 ...
2291                                                NaN
2292                                                NaN
2293                                                NaN
2294                                                NaN
2295                                                NaN

                                                  count  \
0     <span class="andes-visually-hidden">Calificaci...
1     <span class="andes-visually-hidden">Calificaci...
2     <span class="andes-visually-hidden">Calificaci...
3     <span aria-hidden="true" class="andes-visually...
4     <span class="andes-visually-hidden">Calificaci...
...                                                 ...
2291                                                NaN
2292                                                NaN
2293                                                NaN
2294                                                NaN
2295                                                NaN

                                              post link  \
0     https://click1.mercadolibre.com.co/mclics/clic...
1     https://click1.mercadolibre.com.co/mclics/clic...
2     https://articulo.mercadolibre.com.co/MCO-82124...
3     https://articulo.mercadolibre.com.co/MCO-95903...
4     https://articulo.mercadolibre.com.co/MCO-99284...
...                                                 ...
2291  https://articulo.mercadolibre.com.co/MCO-99282...
2292  https://articulo.mercadolibre.com.co/MCO-10202...
2293  https://articulo.mercadolibre.com.co/MCO-10209...
2294  https://articulo.mercadolibre.com.co/MCO-10633...
2295  https://articulo.mercadolibre.com.co/MCO-11158...

                                             image link calificacion  \
0     https://http2.mlstatic.com/D_NQ_NP_820360-MCO7...          4.8
1     https://http2.mlstatic.com/D_NQ_NP_962071-MCO7...          4.8
2     https://http2.mlstatic.com/D_NQ_NP_730331-MCO4...          4.7
3     https://http2.mlstatic.com/D_NQ_NP_636753-MCO5...         None
4     https://http2.mlstatic.com/D_NQ_NP_658192-MCO5...          4.6
...                                                 ...          ...
2291  https://http2.mlstatic.com/D_NQ_NP_931544-MCO5...         None
2292  https://http2.mlstatic.com/D_NQ_NP_981457-MCO5...         None
2293  https://http2.mlstatic.com/D_NQ_NP_892430-MCO4...         None
2294  https://http2.mlstatic.com/D_NQ_NP_875739-MCO5...         None
2295  https://http2.mlstatic.com/D_NQ_NP_836920-MCO5...         None

      opiniones  descuento
0          45.0        7.0
1          10.0       16.0
2         223.0       25.0
3           NaN        6.0
4          25.0        NaN
...         ...        ...
2291        NaN        NaN
2292        NaN        NaN
2293        NaN        NaN
2294        NaN        NaN
2295        NaN        NaN

[2296 rows x 10 columns]

In [ ]:
# Convertir las columnas 'price' y 'calificacion' a tipo float64
#df['price'] = df['price'].astype('float64')
df['price'] = df['price'].str.replace('.', '').astype('float64')
df['calificacion'] = df['calificacion'].astype('float64')

<ipython-input-149-1418d5d23339>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['price'] = df['price'].str.replace('.', '').astype('float64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2296 entries, 0 to 2295
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2296 non-null   int64
 1   title         2296 non-null   object
 2   price         2296 non-null   float64
 3   perc_desc     760 non-null    object
 4   count         628 non-null    object
 5   post link     2296 non-null   object
 6   image link    2296 non-null   object
 7   calificacion  216 non-null    float64
 8   opiniones     349 non-null    float64
 9   descuento     760 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 179.5+ KB

In [ ]:
df

,Unnamed: 0,title,price,perc_desc,count,post link,image link,calificacion,opiniones,descuento
0,0,Extensión Luces Led Estrella X6 M Luz Navidad ...,97900.0,"<span class=""ui-search-price__discount"">7% OFF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_820360-MCO7...,4.8,45.0,7.0
1,1,Luces De Navidad Cortina Luz Decoracion Navide...,59990.0,"<span class=""ui-search-price__discount"">16% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://click1.mercadolibre.com.co/mclics/clic...,https://http2.mlstatic.com/D_NQ_NP_962071-MCO7...,4.8,10.0,16.0
2,2,Luces De Navidad Cortina Luz Decoracion Navide...,62990.0,"<span class=""ui-search-price__discount"">25% OF...","<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-82124...,https://http2.mlstatic.com/D_NQ_NP_730331-MCO4...,4.7,223.0,25.0
3,3,Luz De Navidad Cortina 3m X 45 Cm Luces Varios...,21900.0,"<span class=""ui-search-price__discount"">6% OFF...","<span aria-hidden=""true"" class=""andes-visually...",https://articulo.mercadolibre.com.co/MCO-95903...,https://http2.mlstatic.com/D_NQ_NP_636753-MCO5...,NaN,NaN,6.0
4,4,Luz Lineal Ledl 100 Mts 1000 Led Luces Navidad...,187000.0,NaN,"<span class=""andes-visually-hidden"">Calificaci...",https://articulo.mercadolibre.com.co/MCO-99284...,https://http2.mlstatic.com/D_NQ_NP_658192-MCO5...,4.6,25.0,NaN
...,...,...,...,...,...,...,...,...,...,...
2291,2291,Luz Cascada 6x2m 480 Led Luces Navidad Multico...,164900.0,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-99282...,https://http2.mlstatic.com/D_NQ_NP_931544-MCO5...,NaN,NaN,NaN
2292,2292,Luces Led Estrellas Y Copos 260 Luces 3m Navid...,109900.0,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10202...,https://http2.mlstatic.com/D_NQ_NP_981457-MCO5...,NaN,NaN,NaN
2293,2293,Cortina Led 3m X 45 Cm 100 Led Multicolor Navi...,27900.0,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10209...,https://http2.mlstatic.com/D_NQ_NP_892430-MCO4...,NaN,NaN,NaN
2294,2294,Cortina Led Intercalada 10 M Navidad 360 Led F...,84900.0,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-10633...,https://http2.mlstatic.com/D_NQ_NP_875739-MCO5...,NaN,NaN,NaN
2295,2295,"Cortina Micro Led Ramal 6x1,8 M 1440 Led Navid...",199900.0,NaN,NaN,https://articulo.mercadolibre.com.co/MCO-11158...,https://http2.mlstatic.com/D_NQ_NP_836920-MCO5...,NaN,NaN,NaN

In [ ]:
df.to_csv(r"/content/sample_data/salida2.csv", sep=";")